FROM node:22-alpine
WORKDIR /app
COPY . .
RUN npm install -g pnpm@10.7.0 && pnpm install && pnpm --filter @rigways/types build && pnpm --filter @rigways/api build
EXPOSE 3000
CMD ["pnpm", "--filter", "@rigways/api", "start"]
